# SPDX-License-Identifier: GPL-2.0
dtbo-y += exynos/exynos2100-universal2100_rev10.dtbo
dtb-y += exynos/exynos5433-tm2e.dtb
dtbo-y += exynos/exynos2100-universal2100_rev11.dtbo
dtbo-y += exynos/exynos2100-universal2100_rev02.dtbo
dtb-y += exynos/exynos5433-tm2.dtb
dtbo-y += exynos/exynos2100-smdk2100.dtbo
dtb-y += exynos/exynos7-espresso.dtb
dtb-$(CONFIG_SOC_EXYNOS2100) += exynos/exynos2100.dtb

dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r02.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r16.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r22.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r18.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r19.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r21.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r20.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_eur_openx_w01_r17.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r20.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r02.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r22.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r18.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r17.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r21.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r16.dtbo
dtbo-$(CONFIG_MODEL_O1S) += samsung/o1s/o1s_kor_singlex_w01_r19.dtbo

dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r18.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r16.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r22.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r17.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r20.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r19.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r02.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_eur_openx_w01_r21.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r02.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r19.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r17.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r16.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r18.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r20.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r21.dtbo
dtbo-$(CONFIG_MODEL_T2S) += samsung/t2s/t2s_kor_singlex_w01_r22.dtbo

dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r16.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r02.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r17.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r21.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r18.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r19.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r22.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_eur_openx_w01_r20.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r02.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r17.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r21.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r22.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r18.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r19.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r23.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r16.dtbo
dtbo-$(CONFIG_MODEL_P3S) += samsung/p3s/p3s_kor_singlex_w01_r20.dtbo

dtbo-$(CONFIG_MODEL_R9S) += samsung/r9s/r9s_eur_openx_w01_r17.dtbo
dtbo-$(CONFIG_MODEL_R9S) += samsung/r9s/r9s_eur_openx_w01_r00.dtbo
dtbo-$(CONFIG_MODEL_R9S) += samsung/r9s/r9s_eur_openx_w01_r18.dtbo

targets += dtbs
DTB_LIST  := $(dtb-y) $(dtbo-y)
always    := $(DTB_LIST)

dtbs: $(addprefix $(obj)/, $(DTB_LIST))

clean-files := *.dtb*
